### ISSUE TITLE
Error in update_cumlative_edgelist with ContactTrace branch

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModelCOVID#9]
Running the test script for Kristin's EpiModelCOVID, I am encountering this error:

```r
	A ERROR occured in module 'initialize.FUN' at step `Initialization Step` (1)
Error: Can't recycle input of size 4 to size 5.
Run `rlang::last_error()` to see where the error occurred.
```

within `update_cumlative_edgelist` specifically at the line:

```r
  terminated_edges <- is.na(el_cuml[["current"]]) & is.na(el_cuml[["stop"]])
  if (any(terminated_edges)) {
    el_cuml[terminated_edges, ][["stop"]] <- at - 1
  }
```

Relevant files for reproducing the error:
1. Script: https://github.com/EpiModel/COVID-ContactTrace/blob/updatePackages/R/03-epi-model-calib.R (use this updatePackages branch for now)
2. Package: https://github.com/EpiModel/EpiModelCOVID/tree/ContactTrace

**Comment by AdrienLeGuillou** [comment]
They were several issues 

- in the initialization module 
    - we must use the new `creat_dat_object` to make sure that `dat` contains all it needs
    - the `update_cumlative_edgelist` was called for 3 networks but only 2 are present
- in the simulation module
    - the `update_cumlative_edgelist` was called for 3 networks but only 2 are present
    - the old `tergmLite::simulate_network` was used

I made the fix for EpiModelCOVID in this PR: https://github.com/EpiModel/EpiModelCOVID/pull/10

I made the fix for COVID-ContactTrace in my fork (I don't have write access on the project) : you can see the diff on the file of interest here: https://github.com/AdrienLeGuillou/COVID-ContactTrace/commit/e8b9ec1c68f8babfc1ed9e8ee0c4e514c5aad89e#diff-781a66bbec625f4eeb901754ba2c9532192d0dcfa107a03ee3d95ae1bac729c7
